# ------------------------------------------
# 1. ISTIO BASE (CRDs)
# ------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.28.0  # Pin your version
      helm:
        valueFiles:
          - $values/platform/istio/values.base.yaml
          - $values/platform/istio/values.istiod.yaml
          - $values/platform/istio/values.gateway.yaml
    - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
      targetRevision: main
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 

---
# ------------------------------------------
# 2. ISTIOD (Control Plane)
# ------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
      targetRevision: main
      ref: values
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.28.0
      helm:
        valueFiles:
          - $values/platform/istio/values.istiod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
# ------------------------------------------
# 3. ISTIO INGRESS (Gateway)
# ------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
      targetRevision: main
      ref: values

    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.28.0
      helm:
        valueFiles:
          - $values/platform/istio/values.gateway.yaml

    - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
      targetRevision: main
      path: platform/istio
      directory:
        include: '{certificate.yaml,gateway.yaml,jwt-validation-policy.yaml}'


  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
