replicaCount: 1
image:
  repository: k8s-harbor-harborin-04b31170bb-1679859835.us-east-1.elb.amazonaws.com/phoenix-project/phoenix-api-gateway-service
  tag: "5a960badd374e01bced430311978d97f155104f2"
service:
  port: 7008
serviceAccount:
  name: api-gateway-sa
resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "768Mi"
    cpu: "700m"
env:
  - name: IDENTITY_SERVICE_URL
    value: "http://identity-service"
  - name: HOTEL_SERVICE_URL
    value: "http://hotel-service"
  - name: BOOKING_SERVICE_URL
    value: "http://booking-service"
  - name: SEARCH_SERVICE_URL
    value: "http://search-service"
  - name: JWT_SECRET_KEY
    value: "my-super-secret-key-change-this-later"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://otel-collector.observability:4317
  - name: OTEL_SERVICE_NAME
    value: api-gateway
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: service.namespace=phoenix-app,service.name=api-gateway,deployment.environment=prod
