apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.asgardeoConfig.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.asgardeoConfig.name }}
    app.kubernetes.io/part-of: {{ .Values.global.partOf }}
data:
{{- range $k, $v := .Values.asgardeoConfig.data }}
  {{ $k }}: |
{{ $v | indent 4 }}
{{- end }}
