apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
{{- range $k, $v := .Values.global.namespaceLabels }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
    app.kubernetes.io/part-of: {{ .Values.global.partOf | quote }}
  annotations:
{{- range $k, $v := .Values.global.namespaceAnnotations }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
